version: "3.4"

services:
  app:
    image: buiyenit/reactjs:v1
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_PUBLIC=https://host.docker.internal
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
