version: "3.4"

services:
  app:
    image: buiyenit/reactjs:v1
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./KBHM:/app/src
    ports:
      - "443:443"
    restart: unless-stopped
