version: "3.4"

services:
  app:
    image: ${{DOCKER_REG}}/fekbhm:v1
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
