using BloodBank.api.interfaces;
using BloodBank.api.Model;
using Services.lib.BloodBank;
using Services.lib.Sql;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BloodBank.api.command
{
    public class SyncPatient : ISyncDonnor
    {
        private async Task<HttpObject.APIMapper<SequenceNumInfo>> GetNextSequence()
        {

            string sql = "Select SequenceId, StartNum, EndNum, CurrentVal, Mode, UpdateTime, getdate() as ServerTime " +
                "from dbo.SequenceConfig  where SequenceId=@SequenceId ";
            var sequenceNum = await Services.lib.Sql.Dataprovider.db._Query(sql)._ParamterSQL(new { SequenceId = SequenceNumInfo.SequenceIDIdentityID }).QueryMapperSingleOrDefaultAsync<SequenceNumInfo>();
            if (sequenceNum != null)
            {
                long nextVal = sequenceNum.CurrentVal + 1;
                if (nextVal > sequenceNum.EndNum)
                {
                    //result.CurrentVal = result.StartNum;
                    nextVal = sequenceNum.StartNum;
                }
                else
                {
                    switch (sequenceNum.ResetMode)
                    {
                        case SequenceResetMode.ByYear:
                            if (sequenceNum.ServerTime.Year != sequenceNum.LastUpdate.Year)
                            {
                                sequenceNum.CurrentVal = sequenceNum.StartNum;
                                nextVal = sequenceNum.CurrentVal + 1;
                            }
                            break;
                        case SequenceResetMode.ByMonth:
                            if (sequenceNum.ServerTime.Year != sequenceNum.LastUpdate.Year ||
                                sequenceNum.ServerTime.Month != sequenceNum.LastUpdate.Month)
                            {
                                sequenceNum.CurrentVal = sequenceNum.StartNum;
                                nextVal = sequenceNum.CurrentVal + 1;
                            }
                            break;
                        case SequenceResetMode.ByDay:
                            if (sequenceNum.ServerTime.Year != sequenceNum.LastUpdate.Year ||
                                sequenceNum.ServerTime.Month != sequenceNum.LastUpdate.Month ||
                                sequenceNum.ServerTime.Date != sequenceNum.LastUpdate.Date)
                            {
                                sequenceNum.CurrentVal = sequenceNum.StartNum;
                                nextVal = sequenceNum.CurrentVal + 1;
                            }
                            break;
                    }
                }
                string SQL = "update dbo.SequenceConfig  set CurrentVal = @CurrentVal, UpdateTime = getdate()  where SequenceId=@SequenceId";
                await Services.lib.Sql.Dataprovider.db._Query(SQL)._ParamterSQL(new { CurrentVal = nextVal, SequenceId = SequenceNumInfo.SequenceIDIdentityID }).QueryMapperSingleOrDefaultAsync<SequenceNumInfo>();

            }
            var data = new HttpObject.APIMapper<SequenceNumInfo>();
            data.code = sequenceNum != null ? HttpObject.Enums.Httpstatuscode_API.OK : HttpObject.Enums.Httpstatuscode_API.ERROR;
            data.Data = sequenceNum;
            data.Messenger = "";
            return data;
        }
        private async Task<int?> GetDonorIdByIdentityID(string identityID)
        {
            int? result = null;
            string sql = "select top 1 d.DonorID " +
                     " from tbl_Donor d " +
                     " where d.IdentityID = @IdentityID ";
            var data = await Services.lib.Sql.Dataprovider.db._Query(sql)._ParamterSQL(identityID).SingleOrDefaultAsync();
            if (data.code == HttpObject.Enums.Httpstatuscode_API.OK)
            {
                result = data.Data.DonorID;
            }
            return result;
        }
        private string GetAutoGeneratedIdentityID()
        {
            int? foundDonorId = null;
            string identityID = string.Empty;
            int loopTime = 0;
            do
            {
                DateTime currentDate = DateTime.Now;
                var sequenceNum = GetNextSequence();
                identityID = string.Format("{0:yyMM}{1:0000}", currentDate, sequenceNum.Result.Data.CurrentVal);
                foundDonorId = GetDonorIdByIdentityID(identityID).Result;
                loopTime++;
                if (loopTime > sequenceNum.Result.Data.EndNum - sequenceNum.Result.Data.StartNum)
                {
                    throw new Exception("Không cấp được SID, SID trong ngày đã đầy !!!");
                }
            } while (foundDonorId != null);

            return identityID;
        }
        public async Task<Services.lib.Sql.HttpObject.APIresult> SyncDonnorEx(Donnor.tbl_Donor donnor)
        {
            donnor.Sex = Common.ConvertSex(donnor.Sex);
            donnor.IdentityID = GetAutoGeneratedIdentityID();
            string rowguid = "declare @ID nvarchar(100); set @ID = (select NEWID());";
            string QueryCheckDonnor = @"SELECT * FROM tbl_Donor 
                                                       WHERE IdentityID =@IdentityID ";
            string InsertDonor = "insert into tbl_Donor (DateIn,DonorCode, sex,  Age ,Address,DonorName,DonorNameUnsign,Phone,BirthDay,IdentityID, TypeOf, rowguid  ) values" +
                   "(Getdate(),@DonorCode,@Sex,@Age,@Address,@DonorName,@DonorNameUnsign,@Phone,@BirthDay,@IdentityID,1,@ID );";
            string UpdateDonor = "update tbl_Donor set DonorCode=@DonorCode, sex=@Sex,  Age=@Age ,Address=@Address,DonorName=@DonorName,DonorNameUnsign=@DonorNameUnsign,Phone=@Phone,BirthDay=@BirthDay where IdentityID =@IdentityID";
            string ActionDonnor = @$"BEGIN
                                       IF NOT EXISTS ({QueryCheckDonnor})
                                                       BEGIN
                                                         {InsertDonor}
                                                       END
                                       ELSE
                                                        BEGIN
                                                         {UpdateDonor}
                                                       END
                                    END";
            string SelectDonorEx = "declare @DonorID int; set @DonorID =  (select Top(1)  DonorID from tbl_Donor where rowguid = @ID);";
            string QueryDonorEx = "insert tbl_Donor_Examine (DonorExCode, DonorID,BloodSourceLocationId,BloodVolume,ElementID, DateIn) " +
                "values (@DonorExCode, @DonorID,@BloodSourceLocationId,@BloodVolume,@ElementID, GetDate());";
            string IDSelectDonorEx = "declare @DonorExID int; set @DonorExID =  (select Top(1)  DonorExID from tbl_Donor_Examine where DonorID = @DonorID);";
            string Insert_tbl_Donor_Examine_Attribute = string.Empty;
            string[,] tbl_Donor_Examine_Attribute = new string[,]
            {
                 {"BLOODPRESSURE" ,donnor.BLOODPRESSURE },
                 {"HGB",donnor.HGB},
                 {"PULSE",donnor.PULSE },
                 {"STATUS", donnor.STATUS},
                 {"WEIGH",donnor.WEIGH}
            };
            for (int i = 0; i < tbl_Donor_Examine_Attribute.Length / tbl_Donor_Examine_Attribute.Rank; i++)
            {
                Insert_tbl_Donor_Examine_Attribute += "insert tbl_Donor_Examine_Attribute (DonorExID,ExamineAttributeId ,Value) values " +
                  $"(@DonorExID, N'{tbl_Donor_Examine_Attribute[i, 0]}', N'{tbl_Donor_Examine_Attribute[i, 1]}' );";
            }


            return await Services.lib.Sql.Dataprovider.db._Querys(
                rowguid,
                ActionDonnor,
                SelectDonorEx,
                QueryDonorEx,
                IDSelectDonorEx,
                Insert_tbl_Donor_Examine_Attribute
                )
                ._ParamterSQL(donnor).ExcuteQueryAsync();
        }

        public async Task<HttpObject.APIMapper<dynamic>> CheckDonnorEx(string DonorExCode)
        {
            string SQL = "SELECT cast((case when   count(DonorExCode)  = 1 then 0 else 1 end )  as bit) as CheckDonnor FROM  tbl_Donor_Examine  WHERE (DonorExCode = @DonorExCode)";
            return await Services.lib.Sql.Dataprovider.db._Query(SQL)._ParamterSQL(new { DonorExCode = DonorExCode }).SingleOrDefaultAsync();
        }
    }
}
