version: '3.4'

services:
  ocelot_apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateway/Ocelot_apigateway/Dockerfile

  kbhm.api:
    image: ${DOCKER_REGISTRY-}kbhmapi
    build:
      context: .
      dockerfile: Services/KBHM.api/Dockerfile


  system.api:
    image: ${DOCKER_REGISTRY-}systemapi
    build:
      context: .
      dockerfile: Services/System.api/Dockerfile


  bloodbank.api:
    image: ${DOCKER_REGISTRY-}bloodbankapi
    build:
      context: .
      dockerfile: Services/BloodBank.api/Dockerfile


  serverside:
    image: ${DOCKER_REGISTRY-}reportserver
    ports:
     - "80"


   
