version: '3.4'

services:
  ocelot_apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9874:80"
   
  kbhm.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQLCONNECTION=Server=192.168.61.101,1434;Database=Web_KBHM;User Id=technical;Password=ls109tndq1;TrustServerCertificate=True"
    ports:
      - "80"
      - "443"


  system.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQLCONNECTION=Server=103.157.218.56;Database=ServicesBase;User Id=sa;Password=Buiyen123>;TrustServerCertificate=True"
    ports:
      - "80"
      - "443"


  bloodbank.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQLCONNECTION=Server=host.docker.internal;Database=BloodBank_NhiTW;User Id=sa;Password=Buiyen123>;TrustServerCertificate=True"
    ports:
      - "80"

