version: '3.4'

services:
  ocelot_apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_URLS=http://+:80;https://+:443
    ports:
      - "9874:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


   
  kbhm.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=${MMSQL};Database=Web_KBHM;User Id=technical;Password=ls109tndq1;Encrypt=false;"
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "80"



  system.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=${MMSQL};Database=ServicesBase;User Id=technical;Password=ls109tndq1;Encrypt=false;"
      - "MINIO_CONNECTION=hienmau.bvdktinhthanhhoa.com.vn;9000;vzGdxmLOU5aOECgc;RFcTw59qRxbXVQd6mpTg99wPQcQWLVcP;False;9874"
      - DOMAIN=${DOMAIN}
      - IP=${IP}
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "80"


  bloodbank.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=${MMSQL};Database=BloodBank_DKTH;User Id=technical;Password=ls109tndq1;Encrypt=false;"
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "80"

  
