version: '3.4'

services:
  ocelot_apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=docker
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./hienmau.bvdktinhthanhhoa.com.vn.pfx
    ports:
      - "80"
      - "9874:443"
   
  kbhm.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=192.168.61.101,1434;Database=Web_KBHM;User Id=technical;Password=ls109tndq1;TrustServerCertificate=True;MultipleActiveResultSets=True"
    ports:
      - "80"
      - "443"


  system.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=192.168.61.101,1434;Database=ServicesBase;User Id=technical;Password=ls109tndq1;TrustServerCertificate=True;MultipleActiveResultSets=True"
      - "MINIO_CONNECTION=host.docker.internal;9000;v4vReRf12uqrhlue;3rBBzoyBzseOQhCQzHxy0bcefx5Q8Bv4;False"
    ports:
      - "80"
      - "443"


  bloodbank.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=192.168.61.101,1434;Database=BloodBank_DKTH;User Id=technical;Password=ls109tndq1;TrustServerCertificate=True;MultipleActiveResultSets=True"
    ports:
      - "80"
      - "443"

