version: '3.4'

services:
  ocelot_apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=docker
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/hienmaubvdktinhthanhhoa_com.pfx
      - TZ=Asia/Ho_Chi_Minh
      - NODEELK=${NODEELK}
    volumes:
      - ./Cert/:/https
    ports:
      - "9874:443"
    restart: always

  kbhm.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=${MMSQL};Database=Web_KBHM;User Id=technical;Password=ls109tndq1;TrustServerCertificate=true;"
      - TZ=Asia/Ho_Chi_Minh
      - NODEELK=${NODEELK}
 



  system.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=Server=${MMSQL};Database=ServicesBase;User Id=technical;Password=ls109tndq1;TrustServerCertificate=true;"
      - "MINIO_CONNECTION=${IP};9000;vzGdxmLOU5aOECgc;RFcTw59qRxbXVQd6mpTg99wPQcQWLVcP;True;9874"
      - TZ=Asia/Ho_Chi_Minh
      - DOMAIN=${DOMAIN}
      - IP=${IP}
      - NODEELK=${NODEELK}
   


  bloodbank.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "SQL_CONNECTION=server=${MMSQL};Database=LabconnBBTH_NEW;User Id=technical;Password=ls109tndq1;TrustServerCertificate=true;Pooling=true;Max Pool Size=2000;"
      - "SQL_CONNECTION_REGION1=server=${MMSQL};Database=BloodBank_DKTH;User Id=technical;Password=ls109tndq1;TrustServerCertificate=True;Pooling=true;Max Pool Size=300;"
      - TZ=Asia/Ho_Chi_Minh
      - NODEELK=${NODEELK}
   


