version: '3.4'

services:
  ocelot_apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateway/Ocelot_apigateway/Dockerfile
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
            
         
  kbhm.api:
    image: ${DOCKER_REGISTRY-}kbhmapi
    build:
      context: .
      dockerfile: Services/KBHM.api/Dockerfile
    logging:
      driver: "json-file"
      options:
          max-size: "50m"


  system.api:
    image: ${DOCKER_REGISTRY-}systemapi
    build:
      context: .
      dockerfile: Services/System.api/Dockerfile
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  bloodbank.api:
    image: ${DOCKER_REGISTRY-}bloodbankapi
    build:
      context: .
      dockerfile: Services/BloodBank.api/Dockerfile
    logging:
      driver: "json-file"
      options:
          max-size: "50m"


   
