// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace System.api.Models;

public partial class AmdDmHuyen
{
    public int Id { get; set; }

    public string MaHuyen { get; set; }

    public string TenHuyen { get; set; }

    public int TinhId { get; set; }

    public bool? IsActive { get; set; }
    public ICollection<AmdDmXa> amdDmXas { get; set; }
}