// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace System.api.Models;

public partial class AmdDmXa
{
    public int Id { get; set; }

    public string MaXa { get; set; }

    public string TenXa { get; set; }

    public int HuyenId { get; set; }

    public int TinhId { get; set; }

    public bool? IsActive { get; set; }
}