// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace System.api.Models;

public partial class AmdDmTinh
{
   
    public int Id { get; set; }

    public string MaTinh { get; set; }

    public string TenTinh { get; set; }

    public int QuocgiaId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AmdDmHuyen> AmdDmHuyen { get; set; } = new List<AmdDmHuyen>();

    public virtual AmdDmQuocgia Quocgia { get; set; }
}