name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: buiyenit 
            password: dckr_pat_gR1780vRiyoV3vnjUTZB7Jk4MaE

        -
           run: cd KBHM_BACKEND/KhaiBaoHienMau/;
                ls -a;
                docker-compose -f docker-compose.yml build;
                docker-compose -f docker-compose.yml push;
      
