name: Backend

on:
  push:
    branches: [main]


jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
               
      - name: Login container docker
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASSWORD }}

             
      - name: Build image
        run: | 
         cd KBHM_BACKEND/KhaiBaoHienMau/
          docker-compose -f docker-compose.yml -f docker-compose.override.yml build
          docker-compose -f docker-compose.yml -f docker-compose.override.yml push

        
    
