name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd KBHM_BACKEND/KhaiBaoHienMau/;
           docker-compose -f docker-compose.yml build;
           docker-compose -f docker-compose.yml push;
      
