name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: buiyenit 
          password: dckr_pat_gR1780vRiyoV3vnjUTZB7Jk4MaE

      - name: Build and push Docker images
        run: curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose;
            chmod +x /usr/local/bin/docker-compose;
            cd KBHM_BACKEND/KhaiBaoHienMau/;
            docker-compose -f docker-compose.yml -f docker-compose.override.yml build
            docker-compose -f docker-compose.yml -f docker-compose.override.yml push
 


         
          
      
