name: Server Build & Push

on:
  push:
    branches: [main]


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
               
          
      - name: Build image
        run: | 
         cd KBHM/
          docker-compose -f docker-compose.yml -f docker-compose.override.yml build
           
          
      - name: Login container
        uses: docker/login-action@v2
        with:
           username: "buiyenit"
           password: "dckr_pat_ep_8tWXO20Kuj3wIpVQkluM3TbA"
        
        
      - name: Push image to docker hub
        run: |
          cd KBHM/
          docker-compose -f docker-compose.yml -f docker-compose.override.yml push
